-- SPDX-License-Identifier: Apache-2.0
-- Copyright 2026 PrintForge Contributors

-- Migration 012: Create alerts table
-- NIST 800-53 Rev 5: SI-4 — System Monitoring, AU-2 — Event Logging
--
-- Persists fleet alerts generated by the health/supply/firmware evaluators
-- in pf-fleet-mgr. Every alert is anchored to a printer (FleetAlerts always
-- reference one). `site_id` is denormalized from the printer's
-- location_installation at insert time so admin dashboard queries can
-- scope alerts without a join.
--
-- Alerts pass through three states:
--   Active       — unacknowledged; appears on the dashboard feed.
--   Acknowledged — admin has seen it but the condition persists.
--   Resolved     — underlying condition is cleared.

BEGIN;

CREATE TABLE IF NOT EXISTS alerts (
    id                  UUID        PRIMARY KEY,
    printer_id          TEXT        NOT NULL REFERENCES printers (id),
    site_id             TEXT        NOT NULL DEFAULT '',
    severity            TEXT        NOT NULL
                                    CHECK (severity IN ('Info', 'Warning', 'Critical')),
    category            TEXT        NOT NULL
                                    CHECK (category IN (
                                        'PrinterOffline', 'PrinterError', 'TonerLow',
                                        'PaperLow', 'HealthDegraded', 'FirmwareOutdated',
                                        'StigViolation'
                                    )),
    state               TEXT        NOT NULL DEFAULT 'Active'
                                    CHECK (state IN ('Active', 'Acknowledged', 'Resolved')),
    summary             TEXT        NOT NULL,
    detail              TEXT,
    generated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    acknowledged_at     TIMESTAMPTZ,
    acknowledged_by     TEXT,
    resolved_at         TIMESTAMPTZ
);

-- Query pattern: active alerts for the dashboard feed.
CREATE INDEX IF NOT EXISTS idx_alerts_state_active
    ON alerts (generated_at DESC)
    WHERE state = 'Active';

-- Query pattern: per-site scoping via users/printers join is already fast;
-- this index makes alerts-only site filtering cheap.
CREATE INDEX IF NOT EXISTS idx_alerts_site_id
    ON alerts (site_id)
    WHERE site_id <> '';

-- Query pattern: retention sweeps by age.
CREATE INDEX IF NOT EXISTS idx_alerts_generated_at ON alerts (generated_at DESC);

-- Query pattern: list alerts for a single printer (printer detail view).
CREATE INDEX IF NOT EXISTS idx_alerts_printer_id ON alerts (printer_id);

COMMIT;
