// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 PrintForge Contributors

//! Alert persistence + service layer.
//!
//! [`FleetAlert`](crate::alerting::FleetAlert) is the value type produced by
//! evaluator functions at observation time. This module stores them through
//! their lifecycle (Active → Acknowledged → Resolved) and exposes scoped
//! read / acknowledge APIs consumed by the admin dashboard.
//!
//! **NIST 800-53 Rev 5:** SI-4 — System Monitoring, AU-2 — Event Logging

use std::future::Future;
use std::pin::Pin;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use pf_common::fleet::PrinterId;

use crate::alerting::{AlertCategory, AlertSeverity, FleetAlert};
use crate::error::FleetError;

/// Lifecycle state of a persisted alert.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AlertState {
    /// Unacknowledged; appears on the dashboard feed.
    Active,
    /// Admin has acknowledged it; condition may still persist.
    Acknowledged,
    /// Underlying condition has cleared.
    Resolved,
}

/// An alert row persisted to the database.
///
/// Wraps [`FleetAlert`]'s data with fields the persistence layer owns:
/// durable `id`, denormalized `site_id` (for cheap scope filtering), and the
/// `state` / `acknowledged_by` / `resolved_at` lifecycle columns.
///
/// **NIST 800-53 Rev 5:** SI-4 — System Monitoring
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StoredAlert {
    /// Unique alert identifier.
    pub id: Uuid,
    /// Printer that triggered this alert.
    pub printer_id: PrinterId,
    /// Site / installation, denormalized from the printer at insert time.
    pub site_id: String,
    /// Severity.
    pub severity: AlertSeverity,
    /// Category.
    pub category: AlertCategory,
    /// Lifecycle state.
    pub state: AlertState,
    /// Human-readable summary.
    pub summary: String,
    /// Detailed description, if any.
    pub detail: Option<String>,
    /// When the alert was generated by the evaluator.
    pub generated_at: DateTime<Utc>,
    /// When it was acknowledged, if applicable.
    pub acknowledged_at: Option<DateTime<Utc>>,
    /// EDIPI of the acknowledging admin, if applicable.
    pub acknowledged_by: Option<String>,
    /// When the underlying condition cleared, if applicable.
    pub resolved_at: Option<DateTime<Utc>>,
}

impl StoredAlert {
    /// Build a new `Active` [`StoredAlert`] from a freshly-evaluated
    /// [`FleetAlert`] plus the printer's site attribution.
    #[must_use]
    pub fn from_fleet_alert(alert: FleetAlert, site_id: String) -> Self {
        Self {
            id: alert.id,
            printer_id: alert.printer_id,
            site_id,
            severity: alert.severity,
            category: alert.category,
            state: AlertState::Active,
            summary: alert.summary,
            detail: alert.detail,
            generated_at: alert.generated_at,
            acknowledged_at: alert.acknowledged_at,
            acknowledged_by: None,
            resolved_at: None,
        }
    }
}

/// Persistence interface for stored alerts.
///
/// **NIST 800-53 Rev 5:** SI-4 — System Monitoring
pub trait AlertRepository: Send + Sync {
    /// Insert a new alert row.
    ///
    /// # Errors
    ///
    /// Returns [`FleetError::Repository`] on persistence failure.
    fn insert(
        &self,
        alert: &StoredAlert,
    ) -> impl Future<Output = Result<(), FleetError>> + Send;

    /// List alerts, newest first, paginated and optionally scoped to a set
    /// of installations via the `site_id` column. An empty `installations`
    /// slice means "no site filter".
    ///
    /// **NIST 800-53 Rev 5:** AC-3 — Access Enforcement
    ///
    /// # Errors
    ///
    /// Returns [`FleetError::Repository`] on persistence failure.
    fn list_scoped(
        &self,
        installations: &[String],
        state_filter: Option<AlertState>,
        limit: u32,
        offset: u32,
    ) -> impl Future<Output = Result<(Vec<StoredAlert>, u64), FleetError>> + Send;

    /// Retrieve a single alert by ID.
    ///
    /// # Errors
    ///
    /// Returns [`FleetError::PrinterNotFound`] if no alert exists with the
    /// given ID. (Reuses the not-found variant; see module docs.)
    /// Returns [`FleetError::Repository`] on persistence failure.
    fn get_by_id(
        &self,
        id: Uuid,
    ) -> impl Future<Output = Result<StoredAlert, FleetError>> + Send;

    /// Transition an alert from `Active` to `Acknowledged`, recording the
    /// acknowledging admin's EDIPI and the timestamp.
    ///
    /// # Errors
    ///
    /// Returns [`FleetError::PrinterNotFound`] if no alert has the given ID.
    /// Returns [`FleetError::Repository`] on persistence failure.
    fn acknowledge(
        &self,
        id: Uuid,
        by_edipi: &str,
    ) -> impl Future<Output = Result<StoredAlert, FleetError>> + Send;
}

/// High-level alert service used by the admin dashboard.
///
/// **NIST 800-53 Rev 5:** SI-4 — System Monitoring, AC-3 — Access Enforcement
#[allow(clippy::type_complexity)]
pub trait AlertService: Send + Sync {
    /// List alerts scoped to a set of installations.
    ///
    /// # Errors
    ///
    /// Returns [`FleetError::Repository`] on persistence failure.
    fn list_scoped(
        &self,
        installations: Vec<String>,
        state_filter: Option<AlertState>,
        limit: u32,
        offset: u32,
    ) -> Pin<Box<dyn Future<Output = Result<(Vec<StoredAlert>, u64), FleetError>> + Send + '_>>;

    /// Fetch a single alert by ID. Used by admin handlers to enforce site
    /// scope before a mutation.
    ///
    /// # Errors
    ///
    /// Returns [`FleetError::PrinterNotFound`] if no alert has the given ID.
    /// Returns [`FleetError::Repository`] on persistence failure.
    fn get_by_id(
        &self,
        id: Uuid,
    ) -> Pin<Box<dyn Future<Output = Result<StoredAlert, FleetError>> + Send + '_>>;

    /// Acknowledge an alert by ID.
    ///
    /// # Errors
    ///
    /// Returns [`FleetError::PrinterNotFound`] if no alert has the given ID.
    /// Returns [`FleetError::Repository`] on persistence failure.
    fn acknowledge(
        &self,
        id: Uuid,
        by_edipi: String,
    ) -> Pin<Box<dyn Future<Output = Result<StoredAlert, FleetError>> + Send + '_>>;
}

/// Default `AlertService` implementation backed by an [`AlertRepository`].
pub struct AlertServiceImpl<R> {
    repo: R,
}

impl<R> AlertServiceImpl<R> {
    /// Create a new service wrapping `repo`.
    #[must_use]
    pub fn new(repo: R) -> Self {
        Self { repo }
    }
}

impl<R: AlertRepository + 'static> AlertService for AlertServiceImpl<R> {
    fn list_scoped(
        &self,
        installations: Vec<String>,
        state_filter: Option<AlertState>,
        limit: u32,
        offset: u32,
    ) -> Pin<Box<dyn Future<Output = Result<(Vec<StoredAlert>, u64), FleetError>> + Send + '_>> {
        Box::pin(async move {
            self.repo
                .list_scoped(&installations, state_filter, limit, offset)
                .await
        })
    }

    fn get_by_id(
        &self,
        id: Uuid,
    ) -> Pin<Box<dyn Future<Output = Result<StoredAlert, FleetError>> + Send + '_>> {
        Box::pin(async move { self.repo.get_by_id(id).await })
    }

    fn acknowledge(
        &self,
        id: Uuid,
        by_edipi: String,
    ) -> Pin<Box<dyn Future<Output = Result<StoredAlert, FleetError>> + Send + '_>> {
        Box::pin(async move { self.repo.acknowledge(id, &by_edipi).await })
    }
}

// ── In-memory mock for tests ──────────────────────────────────────────────

#[cfg(test)]
mod in_memory {
    use super::{AlertRepository, AlertState, StoredAlert};
    use crate::error::FleetError;
    use chrono::Utc;
    use std::collections::HashMap;
    use std::sync::Mutex;
    use uuid::Uuid;

    /// In-memory implementation of [`AlertRepository`] for tests.
    #[derive(Default)]
    pub struct InMemoryAlertRepository {
        alerts: Mutex<HashMap<Uuid, StoredAlert>>,
    }

    impl InMemoryAlertRepository {
        /// Create an empty repository.
        #[must_use]
        pub fn new() -> Self {
            Self::default()
        }
    }

    impl AlertRepository for InMemoryAlertRepository {
        async fn insert(&self, alert: &StoredAlert) -> Result<(), FleetError> {
            let mut map = self.alerts.lock().unwrap();
            map.insert(alert.id, alert.clone());
            Ok(())
        }

        async fn list_scoped(
            &self,
            installations: &[String],
            state_filter: Option<AlertState>,
            limit: u32,
            offset: u32,
        ) -> Result<(Vec<StoredAlert>, u64), FleetError> {
            let map = self.alerts.lock().unwrap();
            let mut matches: Vec<StoredAlert> = map
                .values()
                .filter(|a| installations.is_empty() || installations.contains(&a.site_id))
                .filter(|a| state_filter.is_none_or(|s| a.state == s))
                .cloned()
                .collect();
            matches.sort_by(|a, b| b.generated_at.cmp(&a.generated_at));
            let total = matches.len() as u64;
            let page = matches
                .into_iter()
                .skip(offset as usize)
                .take(limit as usize)
                .collect();
            Ok((page, total))
        }

        async fn get_by_id(&self, id: Uuid) -> Result<StoredAlert, FleetError> {
            let map = self.alerts.lock().unwrap();
            map.get(&id).cloned().ok_or(FleetError::PrinterNotFound)
        }

        async fn acknowledge(
            &self,
            id: Uuid,
            by_edipi: &str,
        ) -> Result<StoredAlert, FleetError> {
            let mut map = self.alerts.lock().unwrap();
            let alert = map.get_mut(&id).ok_or(FleetError::PrinterNotFound)?;
            alert.state = AlertState::Acknowledged;
            alert.acknowledged_at = Some(Utc::now());
            alert.acknowledged_by = Some(by_edipi.to_string());
            Ok(alert.clone())
        }
    }
}

#[cfg(test)]
pub use in_memory::InMemoryAlertRepository;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::alerting::{AlertCategory, AlertSeverity};

    fn sample(site: &str, state: AlertState) -> StoredAlert {
        StoredAlert {
            id: Uuid::new_v4(),
            printer_id: PrinterId::new("PRN-0001").unwrap(),
            site_id: site.to_string(),
            severity: AlertSeverity::Critical,
            category: AlertCategory::PrinterOffline,
            state,
            summary: "Printer offline".to_string(),
            detail: None,
            generated_at: Utc::now(),
            acknowledged_at: None,
            acknowledged_by: None,
            resolved_at: None,
        }
    }

    #[tokio::test]
    async fn nist_ac3_list_scoped_filters_by_installations() {
        // NIST 800-53 Rev 5: AC-3 — Access Enforcement
        // Evidence: a site admin sees only their sites' alerts.
        let repo = InMemoryAlertRepository::new();
        repo.insert(&sample("langley", AlertState::Active)).await.unwrap();
        repo.insert(&sample("ramstein", AlertState::Active)).await.unwrap();
        let svc = AlertServiceImpl::new(repo);

        let (page, total) = svc
            .list_scoped(vec!["langley".to_string()], None, 25, 0)
            .await
            .unwrap();
        assert_eq!(total, 1);
        assert_eq!(page.len(), 1);
        assert_eq!(page[0].site_id, "langley");
    }

    #[tokio::test]
    async fn list_scoped_state_filter_excludes_acknowledged() {
        let repo = InMemoryAlertRepository::new();
        repo.insert(&sample("langley", AlertState::Active)).await.unwrap();
        repo.insert(&sample("langley", AlertState::Acknowledged)).await.unwrap();
        let svc = AlertServiceImpl::new(repo);

        let (page, total) = svc
            .list_scoped(Vec::new(), Some(AlertState::Active), 25, 0)
            .await
            .unwrap();
        assert_eq!(total, 1);
        assert_eq!(page.len(), 1);
        assert_eq!(page[0].state, AlertState::Active);
    }

    #[tokio::test]
    async fn acknowledge_transitions_to_acknowledged_with_edipi() {
        let repo = InMemoryAlertRepository::new();
        let alert = sample("langley", AlertState::Active);
        let id = alert.id;
        repo.insert(&alert).await.unwrap();
        let svc = AlertServiceImpl::new(repo);

        let acked = svc.acknowledge(id, "1234567890".to_string()).await.unwrap();
        assert_eq!(acked.state, AlertState::Acknowledged);
        assert_eq!(acked.acknowledged_by.as_deref(), Some("1234567890"));
        assert!(acked.acknowledged_at.is_some());
    }

    #[tokio::test]
    async fn acknowledge_unknown_id_returns_not_found() {
        let repo = InMemoryAlertRepository::new();
        let svc = AlertServiceImpl::new(repo);

        let result = svc
            .acknowledge(Uuid::new_v4(), "1234567890".to_string())
            .await;
        assert!(matches!(result, Err(FleetError::PrinterNotFound)));
    }

    #[test]
    fn from_fleet_alert_starts_active_unacked() {
        let raw = FleetAlert {
            id: Uuid::new_v4(),
            printer_id: PrinterId::new("PRN-0001").unwrap(),
            severity: AlertSeverity::Warning,
            category: AlertCategory::TonerLow,
            summary: "Toner low".to_string(),
            detail: None,
            generated_at: Utc::now(),
            acknowledged: false,
            acknowledged_at: None,
        };
        let stored = StoredAlert::from_fleet_alert(raw, "langley".to_string());
        assert_eq!(stored.state, AlertState::Active);
        assert!(stored.acknowledged_by.is_none());
        assert!(stored.resolved_at.is_none());
        assert_eq!(stored.site_id, "langley");
    }
}
